ARG BUILD_FROM=node:18-alpine
FROM ${BUILD_FROM}

ENV LANG C.UTF-8

RUN apk add --no-cache socat \
 && apk add --no-cache --virtual .build-deps \
      python3 make g++ linux-headers

COPY rootfs/srv/package-lock.json /srv/
COPY rootfs/srv/package.json      /srv/

WORKDIR /srv

RUN npm ci

RUN apk del .build-deps \
 && rm -rf /root/.npm /root/.cache

COPY rootfs/srv/ /srv/

ENTRYPOINT ["node", "/srv/bridge.js"]
